name: Release

on:
  push:
    tags:
      - "v*.*.*" # roda quando criar tag tipo v1.0.0

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binário
        run: cargo build --release

      - name: Renomear binário Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir artifacts
          mv target/release/psy-r artifacts/psyR-${{ github.ref_name }}-linux-x86_64

      - name: Renomear binário macOS
        if: matrix.os == 'macos-latest'
        run: |
          mkdir artifacts
          mv target/release/psy-r artifacts/psyR-${{ github.ref_name }}-macos-x86_64

      - name: Renomear binário Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          move target\release\psy-r.exe artifacts\psyR-${{ github.ref_name }}-windows-x86_64.exe

      - name: Upload binários
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: artifacts/*

  release:
    name: Criar Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar todos os binários
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Preparar changelog
        id: changelog
        run: |
          echo "log<<EOF" >> $GITHUB_OUTPUT
          git fetch --tags
          prev_tag=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          if [ -z "$prev_tag" ]; then
            git log --oneline > commits.txt
          else
            git log $prev_tag..HEAD --oneline > commits.txt
          fi
          cat commits.txt
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Criar Release e Anexar Artefatos
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Mudanças nesta versão
            ${{ steps.changelog.outputs.log }}
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
