name: CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compilar com PyInstaller (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          pyinstaller --onefile --windowed --name="psy-r" \
          --add-data="src/app/assets:app/assets" \
          src/main.py

      - name: Compilar com PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --windowed --name="psy-r" --add-data="src/app/assets;app/assets" src/main.py

      - name: Renomear binário (Linux)
        if: runner.os == 'Linux'
        run: mv dist/psy-r psyR-linux

      - name: Renomear binário (macOS)
        if: runner.os == 'macOS'
        run: mv dist/psy-r psyR-macos

      - name: Renomear binário (Windows)
        if: runner.os == 'Windows'
        run: mv dist/psy-r.exe psyR-windows.exe

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: psyR-${{ matrix.os }}
          path: |
            psyR-linux
            psyR-macos
            psyR-windows.exe
          if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artefatos
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Criar Release e Anexar Artefatos
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
