name: Build and Release

on:
  push:
    tags:
      - 'v*' # O workflow agora só roda quando uma tag é criada

# O gatilho de pull request e push para a 'main' foi removido
# pois não há mais testes para serem executados nesses eventos.
#  pull_request:
#    branches: [ main ]
#  push:
#    branches: [ main ]

permissions:
  contents: write

jobs:
  # O job 'test' foi completamente removido daqui.

  build:
    # A linha 'needs: test' foi removida, pois o job de teste não existe mais.
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Compilar com PyInstaller (Linux/macOS)
        if: runner.os != 'Windows'
        run: pyinstaller --onefile --windowed --name="psy-r" --add-data="src/app/assets:app/assets" src/main.py
      - name: Compilar com PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --windowed --name="psy-r" --add-data="src/app/assets;app/assets" src/main.py
      - name: Renomear binário
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then mv dist/psy-r psyR-linux; fi
          if [ "${{ runner.os }}" == "macOS" ]; then mv dist/psy-r psyR-macos; fi
          if [ "${{ runner.os }}" == "Windows" ]; then mv dist/psy-r.exe psyR-windows.exe; fi
      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: psyR-${{ matrix.os }}
          path: psyR-*

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artefatos
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Criar Release e Anexar Artefatos
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
